name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [Linux]
    runs-on: [ self-hosted, "${{ matrix.os }}" ]
    steps:
      - name: Log masks
        run: echo "::add-mask::$NAME_MASK"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: mlugg/setup-zig@v1
        with: 
          version: master

      - name: Run zig fmt
        if: matrix.os == 'self-hosted'
        run: zig fmt --check .

      - name: Run tests
        run: zig build test -Dmdfunc=$MDFUNC_PATH --summary all
