name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, Windows]
    runs-on: [ self-hosted, "${{ matrix.os }}" ]
    steps:
      - name: Log masks on Linux
        if: matrix.os == 'Linux'
        run: echo "::add-mask::$NAME_MASK"

      - name: Log masks on Windows
        if: matrix.os == 'Windows'
        run: echo "::add-mask::$env:NAME_MASK"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Run zig fmt
        if: matrix.os == 'Linux'
        run: zig fmt --check .

      - name: Run tests
        run: zig build test -freference-trace --summary all
